### ISSUE TITLE
check for float32 not working => creating "segmentation fault"

### ISSUE THREAD

**Issue by khoury** [bioidiap/bob.io.base#1] opened 2015-06-30 13:44 UTC
Hello,
I was getting "segmentation fault" lately while developing some code.
The reason is mainly because the check of the data format is not working properly.
Thank you,
Elie

**Comment by siebenkopf** [comment] 2015-06-30 13:46
Could you please provide more details? Is the bug reproducible?

**Comment by khoury** [comment] 2015-06-30 14:03
Here you are with an example:

import bob.measure
import bob.io.base
import numpy 
import random
pos = numpy.array([1 + random.random() for _ in xrange(10000000)]).astype(numpy.float32)
neg = numpy.array( [1 + random.random() for _ in xrange(1000000)]).astype(numpy.float32)
threshold = bob.measure.eer_threshold(neg, pos)

**Comment by anjos** [comment] 2015-07-01 13:10
@siebenkopf: Are you still handling this one?

**Comment by siebenkopf** [comment] 2015-07-01 13:37
It was a farewell joke that Elie and Laurent had for me, i.e., that they've assigned me.

In fact, it would be nice if you could take over. I guess you have more experience with the bob.measure package.

**Comment by anjos** [comment] 2015-07-01 13:40
Ok, thanks - just did it.

**Comment by tiagofrepereira2012** [comment] 2015-07-16 14:21
Hey, 

I don't understand why this issue was opened here.
Can anyone explain why?

According to @khoury  example, the problem is with this converter here: https://github.com/bioidiap/bob.measure/blob/master/bob/measure/main.cpp#L18

I fixed locally and it is working now.

Thanks

**Comment by tiagofrepereira2012** [comment] 2015-07-16 14:52
Fixed with this pull request https://github.com/bioidiap/bob.measure/pull/1

**Closed by tiagofrepereira2012** 2015-07-16 14:52 UTC
